namespace HealthClinicApp.Entities;

// =====================================================
// Appointment Class
// This class represents the Appointment table in the
// database.
//
// Each object of this class stores the details of
// one appointment.
// =====================================================

public class Appointment
{
    // Stores the Appointment Id
    // This value is automatically generated by the database.
    public int AppointmentId { get; set; }

    // Stores the Doctor Id
    public int DoctorId { get; set; }

    // Stores the Patient Id
    public int PatientId { get; set; }

    // Stores the appointment date
    public DateTime AppointmentDate { get; set; }

    // =====================================================
    // Parameterized Constructor
    // This constructor is used to initialize the object
    // with values at the time of object creation.
    // =====================================================
    public Appointment(int appointmentId, int doctorId, int patientId, DateTime appointmentDate)
    {
        AppointmentId = appointmentId;
        DoctorId = doctorId;
        PatientId = patientId;
        AppointmentDate = appointmentDate;
    }
}